version: 0.2
phases:
  post_build:
    commands:
      - echo Build and install Lambda
      - cd Lambda
      - rm -rf node_modules/
      - npm install --production
      - npm run zipLambda
      - aws lambda update-function-code --function-name NYTStoriesMgmt --zip-file fileb://lambda.zip
      - cd ..
      - echo Building React app
      - rm -rf node_modules/
      - npm install --production
      - npm run build-react
      - echo Zip and deploy the node Elastic Beanstalk app
      - npm run zipForEB
      - echo $CODEBUILD_BUILD_NUMBER
      - echo $CODEBUILD_SOURCE_VERSION
      - aws s3 cp eb.zip s3://elasticbeanstalk-ap-east-1-870258253080/serverProd.zip
      - aws elasticbeanstalk create-application-version --application-name newswatcher --version-label "$CODEBUILD_BUILD_NUMBER" --source-bundle S3Bucket="elasticbeanstalk-ap-east-1-870258253080",S3Key="serverProd.zip"
      - aws elasticbeanstalk update-environment --application-name newswatcher --environment-name Newswatcher-env --version-label "$CODEBUILD_BUILD_NUMBER"
